# Generated by Django 4.1.5 on 2023-03-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_menu_menu_item_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='last_name',
            new_name='Last_name',
        ),
    ]
